# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:*'
        - 's3:ListBucket'
        - 's3:GetBucket'
        - 's3:GetBucketLocation'
        - 'dynamodb:Query'
      Resource: 
        - 'arn:aws:s3:::s3-bucket-cs493'
        - 'arn:aws:s3:::s3-bucket-cs493/*'
        - 'arn:aws:dynamodb:us-west-2:621940852840:table/music'
        
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: 
          path: /
          method: get
          cors: true
      - http: "ANY {proxy+}"
